import '@styles/globals.css';
import Nav from '@components/Nav'
import Provider from '@components/Provider'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create n ext app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body>
        <Provider>
          <div className='main'>
            <div className='gradient'></div>
          </div>
          <main className="app">
            <Nav />
            {children}
          </main>
        </Provider>
      </body>
    </html>
  )
}
